### ISSUE TITLE
Footprint is wrong for TPS55340

### ISSUE THREAD

**Issue by brycedcarter** [PetRover/board#1]
![image](https://cloud.githubusercontent.com/assets/3966935/9830027/542a4d98-58ed-11e5-9eca-5a572b8c527f.png)

![image](https://cloud.githubusercontent.com/assets/3966935/9830043/b4b21cae-58ed-11e5-8eb4-aba7e06ca3d0.png)

**Comment by nnewhart** [comment]
done
