### ISSUE TITLE
STOQ023251 not wide enough

### ISSUE THREAD

**Issue by ajbezreh** [PetRover/board#12]
New to this software, but I think the center of the pin to the outside of the package should be 2.6mm, and it's far less than that. 
![image](https://cloud.githubusercontent.com/assets/13488175/9948246/773e1b58-5d6f-11e5-9c70-5c2e10dfc975.png)

In the image below, the grid is set to 2.6mm (my way of showing that it's not wide enough?
![image](https://cloud.githubusercontent.com/assets/13488175/9948265/a1fe0f92-5d6f-11e5-8692-41a3ebe4b416.png)

**Comment by ajbezreh** [comment]
Also, does it need to be 9.2mm in the other direction? It's currently 2.4mm. 
![image](https://cloud.githubusercontent.com/assets/13488175/9948336/0d6f35f8-5d70-11e5-93de-24d3a8c83432.png)
Not sure if these dimensions mattered, but I figured it might change spacings on the board if they're actually different.

**Comment by ajbezreh** [comment]
If it is an issue, then it's also an issue with the 4 pin connector
![image](https://cloud.githubusercontent.com/assets/13488175/9948453/361721e0-5d71-11e5-8543-651de7962036.png)

**Comment by brycedcarter** [comment]
fixed
