### ISSUE TITLE
Spacing too small on DEA202450BT-1294C1-H

### ISSUE THREAD

**Issue by ajbezreh** [PetRover/board#13]
Still might be doing this wrong, but I read this as the spacing should be 0.25mm

![image](https://cloud.githubusercontent.com/assets/13488175/9948594/78cd9180-5d72-11e5-9ca2-ae2cc1f4b391.png)

and in ours, it's definitely not that big (I made the grid 0.25mm, and a grid square is definitely bigger than the gap)

![image](https://cloud.githubusercontent.com/assets/13488175/9948609/b9bc6626-5d72-11e5-9d8f-45b20ee5f078.png)

**Comment by brycedcarter** [comment]
fixed
