### ISSUE TITLE
Add power pad to TPS55340

### ISSUE THREAD

**Issue by brycedcarter** [PetRover/board#2]
![image](https://cloud.githubusercontent.com/assets/3966935/9830141/b9380718-58f0-11e5-8bcf-c86e13f4811d.png)

**Comment by nnewhart** [comment]
I remember seeing this when I was making the footprint, but wasn't sure what to connect the pad to? Is it not connected to anything? or is it exposed ground?

**Comment by brycedcarter** [comment]
yes, it should be connected to AGND... but that can happen during layout. For the footprint itself, you just need to make a solder mask defined pad where the underlying copper is 5X3.4 and the exposed copper is 2.31X2.64

**Comment by brycedcarter** [comment]
[here](http://eagle.support.eng.narkive.com/FxgvYbra/how-do-i-do-a-solder-mask-defined-pad-with-eagle) is a link for how to do solder mask defined pads

**Comment by brycedcarter** [comment]
Done
![image](https://cloud.githubusercontent.com/assets/3966935/9974511/9a50b406-5e60-11e5-862f-f971e0e46357.png)
